import Link from "next/link";
import type { Metadata } from "next";
import Reveal from "@/components/Reveal";

export const metadata: Metadata = {
  title: "Studio",
  description:
    "Commission interactive installations, audio-reactive visuals, generative design systems, and creative-coding workshops from Ujjwal Agarwal — Bangalore.",
};

const MAIL = "agarwal.ujjwal@gmail.com";
const SUBJECT = encodeURIComponent("Commission enquiry — [project / venue]");

type Service = {
  n: string;
  title: string;
  blurb: string;
  anchor: string;
  examples: { label: string; href: string }[];
};

const SERVICES: Service[] = [
  {
    n: "01",
    title: "Experiential websites & apps",
    blurb:
      "Sites and apps that behave like artworks — generative, alive to time, sound and touch. From a launch microsite people actually remember to a full product, designed and shipped end-to-end.",
    anchor: "from ₹1,50,000",
    examples: [
      { label: "Raga.fm", href: "/work/raga-fm" },
      { label: "Karma", href: "/work/karma" },
    ],
  },
  {
    n: "02",
    title: "Interactive installations",
    blurb:
      "Screen and projection pieces for lobbies, experience centres, museums and events. Body-sensitive, sensor-aware software built to run unattended for years — delivered ready to run on your venue's displays, alongside your AV team.",
    anchor: "from ₹3,00,000",
    examples: [
      { label: "Timelines", href: "/work/timelines" },
      { label: "Pushpak Vimaan", href: "/work/pushpak-vimaan" },
    ],
  },
  {
    n: "03",
    title: "Audio-reactive & live visuals",
    blurb:
      "Real-time stage visuals for concerts, festivals and launches — systems that listen and respond, not pre-rendered loops. Delivered as a performable rig or run live by me.",
    anchor: "from ₹80,000",
    examples: [
      { label: "Silent Night", href: "/work/silent-night" },
      { label: "Control", href: "/work/control" },
    ],
  },
  {
    n: "04",
    title: "Generative systems & editions",
    blurb:
      "Brand systems that draw themselves, data-driven artwork, and pen-plotted editions — identities and objects generated by code, unique in every instance.",
    anchor: "from ₹1,50,000",
    examples: [{ label: "Riddle", href: "/work/riddle" }],
  },
  {
    n: "05",
    title: "Workshops & training",
    blurb:
      "Creative coding, generative art and real-time graphics for teams, studios and institutions — from a half-day taster to a week-long intensive. Years of teaching practice, hands-on from the first hour.",
    anchor: "from ₹60,000 / day",
    examples: [],
  },
];

const PROCESS: { n: string; title: string; body: string }[] = [
  {
    n: "01",
    title: "Brief",
    body: "A call, or a walk through the space. We define the audience, the screens, the budget band, and what the piece must do.",
  },
  {
    n: "02",
    title: "Concept & fixed quote",
    body: "You get a concept note with sketches, a tech spec, a timeline, and a fixed price. No surprises later.",
  },
  {
    n: "03",
    title: "Build in the open",
    body: "Weekly live demos as the work takes shape — you watch the piece come alive in the browser, not in a slide deck.",
  },
  {
    n: "04",
    title: "Launch & handover",
    body: "Deployment, calibration on your displays alongside your AV partner, and clean documentation. Optional software retainer so it keeps running beautifully.",
  },
];

export default function Studio() {
  return (
    <section
      className="wrap"
      style={{
        paddingTop: "clamp(9rem, 18vh, 13rem)",
        paddingBottom: "clamp(6rem, 14vh, 12rem)",
      }}
    >
      <Reveal>
        <header style={{ marginBottom: "clamp(3rem, 7vh, 5rem)" }}>
          <span className="mono" style={{ color: "var(--saffron)" }}>
            Commissions &amp; collaborations
          </span>
          <h1 style={{ fontSize: "var(--step-4)", marginTop: "1.2rem" }}>
            Studio
          </h1>
          <p
            style={{
              marginTop: "1.6rem",
              maxWidth: "56ch",
              fontSize: "var(--step-1)",
              lineHeight: 1.45,
              color: "var(--bone-dim)",
            }}
          >
            I build systems that make art — experiential websites and apps,
            interactive installations, audio-reactive stages and generative
            identities, commissioned by brands, venues and institutions.
            Software, designed and shipped end-to-end. Based in Bangalore,
            working anywhere.
          </p>
          <div
            style={{
              marginTop: "2rem",
              display: "flex",
              flexWrap: "wrap",
              alignItems: "center",
              gap: "1.4rem",
            }}
          >
            <a className="cta" href={`mailto:${MAIL}?subject=${SUBJECT}`}>
              Start a commission <span className="arrow">↗</span>
            </a>
            <span className="mono" style={{ color: "var(--ash)" }}>
              Now booking Sep — Dec 2026
            </span>
          </div>
        </header>
      </Reveal>

      {/* services */}
      <div
        style={{
          borderBottom: "1px solid var(--line)",
          paddingBottom: "1.2rem",
          marginBottom: "0.5rem",
          display: "flex",
          justifyContent: "space-between",
        }}
      >
        <span className="mono" style={{ color: "var(--ash)" }}>
          What the studio makes
        </span>
        <span className="mono" style={{ color: "var(--ash)" }}>
          ({String(SERVICES.length).padStart(2, "0")})
        </span>
      </div>

      <ul style={{ listStyle: "none", margin: 0, padding: 0 }}>
        {SERVICES.map((s) => (
          <li
            key={s.n}
            className="work-row"
            style={{
              padding: "clamp(1.4rem, 3vw, 2.4rem) 0",
              borderBottom: "1px solid var(--line)",
            }}
          >
            <span className="mono" style={{ color: "var(--ash)" }}>
              {s.n}
            </span>
            <span
              style={{ display: "flex", flexDirection: "column", gap: "0.6rem" }}
            >
              <span
                style={{
                  fontFamily: "var(--font-display)",
                  fontSize: "var(--step-2)",
                  lineHeight: 1,
                  color: "var(--bone)",
                }}
              >
                {s.title}
              </span>
              <span style={{ color: "var(--bone-dim)", maxWidth: "52ch" }}>
                {s.blurb}
              </span>
              {s.examples.length > 0 && (
                <span
                  className="mono"
                  style={{
                    display: "flex",
                    flexWrap: "wrap",
                    gap: "1.1rem",
                    marginTop: "0.3rem",
                    color: "var(--ash)",
                  }}
                >
                  {s.examples.map((e) => (
                    <Link key={e.href} className="link" href={e.href}>
                      {e.label} →
                    </Link>
                  ))}
                </span>
              )}
            </span>
            <span
              className="mono work-row__meta"
              style={{ color: "var(--saffron)", whiteSpace: "nowrap" }}
            >
              {s.anchor}
            </span>
          </li>
        ))}
      </ul>

      {/* process */}
      <Reveal>
        <div style={{ marginTop: "clamp(4rem, 9vh, 7rem)" }}>
          <div
            style={{
              borderBottom: "1px solid var(--line)",
              paddingBottom: "1.2rem",
              marginBottom: "clamp(1.5rem, 4vh, 2.5rem)",
            }}
          >
            <span className="mono" style={{ color: "var(--ash)" }}>
              How a commission works
            </span>
          </div>
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(auto-fit, minmax(15rem, 1fr))",
              gap: "clamp(1.5rem, 3vw, 2.5rem)",
            }}
          >
            {PROCESS.map((p) => (
              <div
                key={p.n}
                style={{ display: "flex", flexDirection: "column", gap: "0.7rem" }}
              >
                <span className="mono" style={{ color: "var(--saffron)" }}>
                  {p.n}
                </span>
                <span
                  style={{
                    fontFamily: "var(--font-display)",
                    fontSize: "var(--step-1)",
                    lineHeight: 1.1,
                  }}
                >
                  {p.title}
                </span>
                <span style={{ color: "var(--bone-dim)" }}>{p.body}</span>
              </div>
            ))}
          </div>
        </div>
      </Reveal>

      {/* credibility strip */}
      <Reveal>
        <p
          style={{
            marginTop: "clamp(4rem, 9vh, 7rem)",
            maxWidth: "58ch",
            fontSize: "var(--step-1)",
            lineHeight: 1.5,
            color: "var(--bone-dim)",
          }}
        >
          Generative artist since 2017. MA Computational Arts, Goldsmiths,
          University of London. Faculty at Srishti Manipal Institute of Art,
          Design &amp; Technology. Recent studio work spans experiential
          concepts for biotech campuses, airports and cultural institutions.
        </p>
      </Reveal>

      {/* closing CTA */}
      <Reveal>
        <div
          style={{
            marginTop: "clamp(3rem, 7vh, 5rem)",
            paddingTop: "clamp(2rem, 5vh, 3rem)",
            borderTop: "1px solid var(--line)",
            display: "flex",
            flexWrap: "wrap",
            alignItems: "baseline",
            justifyContent: "space-between",
            gap: "1.5rem",
          }}
        >
          <span
            style={{
              fontFamily: "var(--font-display)",
              fontSize: "var(--step-3)",
              lineHeight: 1,
            }}
          >
            Have a space that needs a soul?
          </span>
          <a className="cta" href={`mailto:${MAIL}?subject=${SUBJECT}`}>
            {MAIL} <span className="arrow">↗</span>
          </a>
        </div>
      </Reveal>
    </section>
  );
}
